### ISSUE TITLE
Problem during rendering of the dashborad

### ISSUE THREAD

**Issue by paoloCastroPullmedia** [sonata-project/SonataTimelineBundle#104]
Hello I have this message during the rendering of my dashbord ins sonata admin

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_3 FROM (SELECT t0_.context AS context_0, t0_.type AS type_1, t0_.created_at AS created_at_2, t0_.id AS id_3, t1_.verb AS verb_4, t1_.status_current AS status_current_5, t1_.status_wanted AS status_wanted_6, t1_.duplicate_key AS duplicate_key_7, t1_.duplicate_priority AS duplicate_priority_8, t1_.created_at AS created_at_9, t1_.id AS id_10, t2_.type AS type_11, t2_.text AS text_12, t2_.id AS id_13, t3_.model AS model_14, t3_.identifier AS identifier_15, t3_.hash AS hash_16, t3_.id AS id_17 FROM timeline__timeline t0_ INNER JOIN timeline__action t1_ ON t0_.action_id = t1_.id LEFT JOIN timeline__action_component t2_ ON t1_.id = t2_.action_id LEFT JOIN timeline__component t3_ ON t2_.component_id = t3_.id WHERE t0_.type = ? AND t0_.context = ? AND t0_.subject_id = ?) dctrn_result ORDER BY created_at_2 DESC LIMIT 25 OFFSET 0' with params ["timeline", "SONATA_ADMIN", 1]:

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.created_at_2' which is not in SELECT list; this is incompatible with DISTINCT").

Could you help me, my configuration of sonata Timeline it's exactly the on in the doc

Thx 
Paolo

**Comment by greg0ire** [comment]
Why did you ignore the issue template?

**Comment by paoloCastroPullmedia** [comment]
the template is working fine when i'm not adding the block timeline.

 when i had the block time line i get this message

**Comment by greg0ire** [comment]
I mean the issue template that asks you for information when you fill a github issue

**Comment by greg0ire** [comment]
Closing as duplicate
