### ISSUE TITLE
Remove deprecations for symfony 3.0

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataTimelineBundle#108]
The following classes use deprecated method / services:

Usage of `SecurityContextInterface`
- `Sonata\TimelineBundle\Admin\AdminExtension::__construct`
- `Sonata\TimelineBundle\Block\TimelineBlock::__construct`

**Comment by msalmikais** [comment]
how to solve the problem of this bundle for symfony 3.0 ?
i have this error : 
`The service "sonata.timeline.admin.extension" has a dependency on a non-existent service "security.context".`

**Comment by core23** [comment]
Simply, we need to fix DI for both mentioned classes. Can you do this @msalmikais ?

**Comment by msalmikais** [comment]
it will be with pleasure, but I am novice with symfony.
What is DI? can you guide me?

**Comment by greg0ire** [comment]
Looks like you already took care of the first one @core23 : https://github.com/sonata-project/SonataTimelineBundle/pull/112

**Comment by greg0ire** [comment]
What version of the bundle do you use @msalmikais ?

**Comment by core23** [comment]
> Looks like you already took care of both classes @core23 : https://github.com/sonata-project/SonataTimelineBundle/pull/112

I'm tired too 😆

**Comment by msalmikais** [comment]
@greg0ire  : sonata-project/timeline-bundle 3.0.0

**Comment by core23** [comment]
This issue was fixed in https://github.com/sonata-project/SonataTimelineBundle/releases/tag/3.1.1

**Comment by greg0ire** [comment]
@msalmikais please do not report issues unless `composer outdated` returns nothing

**Comment by msalmikais** [comment]
ok, and thanks for your help
