### ISSUE TITLE
More than one admin per entity throws exception

### ISSUE THREAD

**Issue by der-kua** [sonata-project/SonataTimelineBundle#13]
The cause of the problem is [here](https://github.com/sonata-project/SonataTimelineBundle/blob/master/Twig/Extension/SonataTimelineExtension.php#L61). Same issue [here](https://github.com/sonata-project/SonataAdminBundle/issues/1899).

Is there a way to provide some kind of default admin for a class?

Regards

**Comment by rande** [comment]
This is fixed
