### ISSUE TITLE
Doctrine Bundle version ^2 not supported

### ISSUE THREAD

**Issue by HugoBroudeur** [sonata-project/SonataTimelineBundle#231]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.56.1 3.56.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.3 3.18.3 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/cache-bundle              3.1.0  3.1.0  This bundle provides caching services
sonata-project/core-bundle               3.17.2 3.17.2 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.1.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.5.1  1.5.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.13.0 3.13.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.1 2.0.1  Lightweight Exporter library
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/timeline-bundle           3.4.0  3.4.0  Integrates SpyTimelineBundle into Sonata
sonata-project/user-bundle               4.5.1  4.5.1  Symfony SonataUserBundle

```

#### Symfony packages

```
$ composer show --latest 'doctrine/*'
...
doctrine/doctrine-bundle            2.0.6   2.0.6   Symfony DoctrineBundle
...
```

## Subject

Upgrading the doctrine/doctrine-bundle to version 2.* cause the error:

**Argument 1 passed to Sonata\TimelineBundle\Spread\AdminSpread::__construct() must be an instance of Symfony\Bridge\Doctrine\RegistryInterface, instance of Doctrine\Bundle\DoctrineBundle\Registry given**

According to the upgrade notes available here: https://github.com/doctrine/DoctrineBundle/blob/master/UPGRADE-2.0.md

The Symfony\Bridge\Doctrine\RegistryInterface interface is no longer aliased to the doctrine service, use Doctrine\Common\Persistence\ManagerRegistry instead.

In the config file timeline_orm.xml:
***
        <service id="sonata.timeline.spread.admin" class="Sonata\TimelineBundle\Spread\AdminSpread">
            <tag name="spy_timeline.spread"/>
            <argument type="service" id="doctrine"/>
            <argument>%sonata.timeline.admin.user.entity%</argument>
        </service>
***

## Suggestion
The service signature should be updated for the doctrine-bundle version ^2 or add a package dependency.

## Steps to reproduce
upgrade package doctrine/doctrine-bundle to version "2.*" in your composer.json

**Comment by core23** [comment]
Can you please provide a PR with a fix @HugoBroudeur
