### ISSUE TITLE
Untranslated texts

### ISSUE THREAD

**Issue by Warxcell** [sonata-project/SonataTimelineBundle#24]
There are few untranslated texts like:   No action for now ... , Element Deleted and etc. It would be nice to have these translated. Also i think this should be removed:             {% sonata_template_box 'This is the timeline block.' %}

I like bundles with default things.

**Comment by rande** [comment]
@Warxcell ``sonata_template_box`` content are not displayed on prod env.

**Comment by OskarStark** [comment]
"Not action for now...." is fixxed now!

The blue box is discussed here: #38 

please close this ticket @Soullivaneuh @rande
