### ISSUE TITLE
Timeline listing page with filter in sonataadmin bundle

### ISSUE THREAD

**Issue by nepfrank** [sonata-project/SonataTimelineBundle#32]
I am using sonata timeline bundle(which in turn uses this bundle).
I was planning to have a normal actions list page with pagination and some filters.(just like post listing page) but i am totally confused how to get it donw

For normal bundle we made admin controller as follows. But for timeline i don't know what to do. I was able to get some record on dashboard but i want to keep all records as activity log.

What should i do?

class TimelineAdmin extends Admin
{
/**
* {@inheritdoc}
*/

protected function configureDatagridFilters(DatagridMapper $datagridMapper)
{
$datagridMapper
->add('...');
}

protected function configureListFields(ListMapper $listMapper)
{
    $listMapper
        ->addIdentifier('...');
}
}

**Comment by OskarStark** [comment]
can we close this ticket @nepfrank ?

**Comment by nepfrank** [comment]
Where is the answer?
How can i do it?

**Comment by Soullivaneuh** [comment]
Please see doc for admin integration (at the end): https://sonata-project.org/bundles/timeline/master/doc/reference/installation.html

If you want to manage your timeline entity, just configure it as you do for yours.
