### ISSUE TITLE
how to get rid of the blue box?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataTimelineBundle#38]
<img width="714" alt="bildschirmfoto 2015-07-03 um 11 31 23" src="https://cloud.githubusercontent.com/assets/995707/8496632/0fefdefc-2177-11e5-9ba3-6a3f0778b9c6.png">

is there a config?

**Comment by Soullivaneuh** [comment]
Seems not: https://github.com/sonata-project/SonataTimelineBundle/blob/master/Resources/views/Block/timeline.html.twig#L25

![579626](https://cloud.githubusercontent.com/assets/1698357/8496867/d60943ac-2178-11e5-8637-b50b74b74b63.jpg)

:-)

@rande can you confirm? What can we do about that?

**Comment by OskarStark** [comment]
i will have a look at the sonata demo

**Comment by rande** [comment]
@OskarStark the box is only visible with the dev env

**Comment by Soullivaneuh** [comment]
Having an option to completely remove it could be useful, isn't it?

**Comment by OskarStark** [comment]
hmm, but i want to be able to deactivate the blue box in dev mode.

i agree with you @Soullivaneuh 

is this:
```twig
 {% sonata_template_box 'This is the timeline block.' %}
```

used in some other sonata bundles?

**Comment by OskarStark** [comment]
or what do you think about to show this blue box only if there are no actions??

**Comment by Soullivaneuh** [comment]
I would prefer the option way IMO.
