### ISSUE TITLE
Bundle incompatible with Symfony 4.4

### ISSUE THREAD

**Issue by RubixR4** [sonata-project/SonataTimelineBundle#382]
When installing the bundle on a Symfony 4.4 project, there is a dependency conflict.

Doctrine requires `doctrine/persistence ^2.2` whereas the timeline bundle requires `doctrine/persistence ^1.3`. Is there a real reason to avoid the dependancy update or is it possible the simply modify the bundle's composer.json ?

**Comment by VincentLanglet** [comment]
This bundle is abandoned
