### ISSUE TITLE
change context in installation.rst

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataTimelineBundle#42]
if we use GLOBAL as default context here:

```php
    /**
     * {@inheritdoc}
     */
    public function setDefaultSettings(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'max_per_page'    => 10,
            'title'           => 'Latest Actions',
            'template'        => 'SonataTimelineBundle:Block:timeline.html.twig',
            'context'         => 'GLOBAL',
            'filter'          => true,
            'group_by_action' => true,
            'paginate'        => true,
        ));
    }
```

we should change this here, otherwise the user does not see something:
![bildschirmfoto_2015-07-03_um_12_24_54](https://cloud.githubusercontent.com/assets/995707/8497577/b2ad20bc-217e-11e5-8252-8881c3c65a36.jpg)

if you like my idea, let me know and i will create a PR

Oskar

**Comment by OskarStark** [comment]
@Soullivaneuh @rande what do you think?

**Comment by rande** [comment]
@OskarStark The SONATA_ADMIN is used by the admin spreader: https://github.com/sonata-project/SonataTimelineBundle/blob/master/Spread/AdminSpread.php#L62 So we need to keep the value as it. Or am I missing something ?

**Comment by OskarStark** [comment]
@rande hmm you are tight, i didn't get that

but the GOAB is a bit confusing for me..
