### ISSUE TITLE
why is mongodb here not supported?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataTimelineBundle#45]
https://github.com/sonata-project/SonataTimelineBundle/blob/master/DependencyInjection/SonataTimelineExtension.php#L42

in the ConfigurationTreeBuilder ```mongodb``` is allowed.
In the other Methods in ```SonataTimelineExtension``, too.

Shall we fix that?

**Comment by OskarStark** [comment]
@rande

**Comment by rande** [comment]
@OskarStark well there is not work on the sonata's side to make it work with mongodb.

**Comment by OskarStark** [comment]
ok, thanks
