### ISSUE TITLE
only master branch available, no release

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataTimelineBundle#64]
@rande can you create a release for this bundle?

or @core23 can you help me, don't know how to do that

**Comment by core23** [comment]
I could do it, but I think @rande should create the release because he owns this stuff

**Comment by rande** [comment]
We can create a release if every thing is fine. You don't need me to create a release, I trust you :)

**Comment by OskarStark** [comment]
:kissing_heart: :smile:

**Comment by OskarStark** [comment]
@core23 should we update the travis config like in the SonataAdminBundle?

**Comment by core23** [comment]
After https://github.com/sonata-project/SonataTimelineBundle/pull/67 I would create a tag

**Comment by OskarStark** [comment]
:+1:

**Comment by core23** [comment]
Waiting for the next minor release in ``SonataAdminBundle``. After that I would create a last 2.x.x release, before we should start working on the new major release.

**Comment by Soullivaneuh** [comment]
As master branch require old 2.4 unstable admin-bundle. So the next stable version will be 4.0.

I'm working on it today.

**Comment by core23** [comment]
No 3.0 release @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
Sorry, I wanted to say 3.0. :wink:
